/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LayoutmainRouteImport } from './routes/_layoutmain'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LayoutmainZonasRouteImport } from './routes/_layoutmain.zonas'
import { Route as LayoutmainUtilizadoresRouteImport } from './routes/_layoutmain.utilizadores'
import { Route as LayoutmainRotasRouteImport } from './routes/_layoutmain.rotas'
import { Route as LayoutmainReportesRouteImport } from './routes/_layoutmain.reportes'
import { Route as LayoutmainRecolhasRouteImport } from './routes/_layoutmain.recolhas'
import { Route as LayoutmainQuizRouteImport } from './routes/_layoutmain.quiz'
import { Route as LayoutmainPartilhasRouteImport } from './routes/_layoutmain.partilhas'
import { Route as LayoutmainNoticiasRouteImport } from './routes/_layoutmain.noticias'
import { Route as LayoutmainMapaSensoresRouteImport } from './routes/_layoutmain.mapa-sensores'
import { Route as LayoutmainMapaRouteImport } from './routes/_layoutmain.mapa'
import { Route as LayoutmainHomeRouteImport } from './routes/_layoutmain.home'
import { Route as LayoutmainFilaRouteImport } from './routes/_layoutmain.fila'
import { Route as LayoutmainEcopontosRouteImport } from './routes/_layoutmain.ecopontos'
import { Route as LayoutmainDashboardRouteImport } from './routes/_layoutmain.dashboard'
import { Route as LayoutmainConfiguracoesRouteImport } from './routes/_layoutmain.configuracoes'
import { Route as LayoutmainCampanhasRouteImport } from './routes/_layoutmain.campanhas'
import { Route as LayoutmainAuditRouteImport } from './routes/_layoutmain.audit'
import { Route as LayoutmainAnalyticsRouteImport } from './routes/_layoutmain.analytics'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutmainRoute = LayoutmainRouteImport.update({
  id: '/_layoutmain',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutmainZonasRoute = LayoutmainZonasRouteImport.update({
  id: '/zonas',
  path: '/zonas',
  getParentRoute: () => LayoutmainRoute,
} as any)
const LayoutmainUtilizadoresRoute = LayoutmainUtilizadoresRouteImport.update({
  id: '/utilizadores',
  path: '/utilizadores',
  getParentRoute: () => LayoutmainRoute,
} as any)
const LayoutmainRotasRoute = LayoutmainRotasRouteImport.update({
  id: '/rotas',
  path: '/rotas',
  getParentRoute: () => LayoutmainRoute,
} as any)
const LayoutmainReportesRoute = LayoutmainReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => LayoutmainRoute,
} as any)
const LayoutmainRecolhasRoute = LayoutmainRecolhasRouteImport.update({
  id: '/recolhas',
  path: '/recolhas',
  getParentRoute: () => LayoutmainRoute,
} as any)
const LayoutmainQuizRoute = LayoutmainQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => LayoutmainRoute,
} as any)
const LayoutmainPartilhasRoute = LayoutmainPartilhasRouteImport.update({
  id: '/partilhas',
  path: '/partilhas',
  getParentRoute: () => LayoutmainRoute,
} as any)
const LayoutmainNoticiasRoute = LayoutmainNoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => LayoutmainRoute,
} as any)
const LayoutmainMapaSensoresRoute = LayoutmainMapaSensoresRouteImport.update({
  id: '/mapa-sensores',
  path: '/mapa-sensores',
  getParentRoute: () => LayoutmainRoute,
} as any)
const LayoutmainMapaRoute = LayoutmainMapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => LayoutmainRoute,
} as any)
const LayoutmainHomeRoute = LayoutmainHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => LayoutmainRoute,
} as any)
const LayoutmainFilaRoute = LayoutmainFilaRouteImport.update({
  id: '/fila',
  path: '/fila',
  getParentRoute: () => LayoutmainRoute,
} as any)
const LayoutmainEcopontosRoute = LayoutmainEcopontosRouteImport.update({
  id: '/ecopontos',
  path: '/ecopontos',
  getParentRoute: () => LayoutmainRoute,
} as any)
const LayoutmainDashboardRoute = LayoutmainDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LayoutmainRoute,
} as any)
const LayoutmainConfiguracoesRoute = LayoutmainConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => LayoutmainRoute,
} as any)
const LayoutmainCampanhasRoute = LayoutmainCampanhasRouteImport.update({
  id: '/campanhas',
  path: '/campanhas',
  getParentRoute: () => LayoutmainRoute,
} as any)
const LayoutmainAuditRoute = LayoutmainAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => LayoutmainRoute,
} as any)
const LayoutmainAnalyticsRoute = LayoutmainAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => LayoutmainRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/analytics': typeof LayoutmainAnalyticsRoute
  '/audit': typeof LayoutmainAuditRoute
  '/campanhas': typeof LayoutmainCampanhasRoute
  '/configuracoes': typeof LayoutmainConfiguracoesRoute
  '/dashboard': typeof LayoutmainDashboardRoute
  '/ecopontos': typeof LayoutmainEcopontosRoute
  '/fila': typeof LayoutmainFilaRoute
  '/home': typeof LayoutmainHomeRoute
  '/mapa': typeof LayoutmainMapaRoute
  '/mapa-sensores': typeof LayoutmainMapaSensoresRoute
  '/noticias': typeof LayoutmainNoticiasRoute
  '/partilhas': typeof LayoutmainPartilhasRoute
  '/quiz': typeof LayoutmainQuizRoute
  '/recolhas': typeof LayoutmainRecolhasRoute
  '/reportes': typeof LayoutmainReportesRoute
  '/rotas': typeof LayoutmainRotasRoute
  '/utilizadores': typeof LayoutmainUtilizadoresRoute
  '/zonas': typeof LayoutmainZonasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/analytics': typeof LayoutmainAnalyticsRoute
  '/audit': typeof LayoutmainAuditRoute
  '/campanhas': typeof LayoutmainCampanhasRoute
  '/configuracoes': typeof LayoutmainConfiguracoesRoute
  '/dashboard': typeof LayoutmainDashboardRoute
  '/ecopontos': typeof LayoutmainEcopontosRoute
  '/fila': typeof LayoutmainFilaRoute
  '/home': typeof LayoutmainHomeRoute
  '/mapa': typeof LayoutmainMapaRoute
  '/mapa-sensores': typeof LayoutmainMapaSensoresRoute
  '/noticias': typeof LayoutmainNoticiasRoute
  '/partilhas': typeof LayoutmainPartilhasRoute
  '/quiz': typeof LayoutmainQuizRoute
  '/recolhas': typeof LayoutmainRecolhasRoute
  '/reportes': typeof LayoutmainReportesRoute
  '/rotas': typeof LayoutmainRotasRoute
  '/utilizadores': typeof LayoutmainUtilizadoresRoute
  '/zonas': typeof LayoutmainZonasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layoutmain': typeof LayoutmainRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_layoutmain/analytics': typeof LayoutmainAnalyticsRoute
  '/_layoutmain/audit': typeof LayoutmainAuditRoute
  '/_layoutmain/campanhas': typeof LayoutmainCampanhasRoute
  '/_layoutmain/configuracoes': typeof LayoutmainConfiguracoesRoute
  '/_layoutmain/dashboard': typeof LayoutmainDashboardRoute
  '/_layoutmain/ecopontos': typeof LayoutmainEcopontosRoute
  '/_layoutmain/fila': typeof LayoutmainFilaRoute
  '/_layoutmain/home': typeof LayoutmainHomeRoute
  '/_layoutmain/mapa': typeof LayoutmainMapaRoute
  '/_layoutmain/mapa-sensores': typeof LayoutmainMapaSensoresRoute
  '/_layoutmain/noticias': typeof LayoutmainNoticiasRoute
  '/_layoutmain/partilhas': typeof LayoutmainPartilhasRoute
  '/_layoutmain/quiz': typeof LayoutmainQuizRoute
  '/_layoutmain/recolhas': typeof LayoutmainRecolhasRoute
  '/_layoutmain/reportes': typeof LayoutmainReportesRoute
  '/_layoutmain/rotas': typeof LayoutmainRotasRoute
  '/_layoutmain/utilizadores': typeof LayoutmainUtilizadoresRoute
  '/_layoutmain/zonas': typeof LayoutmainZonasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/analytics'
    | '/audit'
    | '/campanhas'
    | '/configuracoes'
    | '/dashboard'
    | '/ecopontos'
    | '/fila'
    | '/home'
    | '/mapa'
    | '/mapa-sensores'
    | '/noticias'
    | '/partilhas'
    | '/quiz'
    | '/recolhas'
    | '/reportes'
    | '/rotas'
    | '/utilizadores'
    | '/zonas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/analytics'
    | '/audit'
    | '/campanhas'
    | '/configuracoes'
    | '/dashboard'
    | '/ecopontos'
    | '/fila'
    | '/home'
    | '/mapa'
    | '/mapa-sensores'
    | '/noticias'
    | '/partilhas'
    | '/quiz'
    | '/recolhas'
    | '/reportes'
    | '/rotas'
    | '/utilizadores'
    | '/zonas'
  id:
    | '__root__'
    | '/'
    | '/_layoutmain'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/_layoutmain/analytics'
    | '/_layoutmain/audit'
    | '/_layoutmain/campanhas'
    | '/_layoutmain/configuracoes'
    | '/_layoutmain/dashboard'
    | '/_layoutmain/ecopontos'
    | '/_layoutmain/fila'
    | '/_layoutmain/home'
    | '/_layoutmain/mapa'
    | '/_layoutmain/mapa-sensores'
    | '/_layoutmain/noticias'
    | '/_layoutmain/partilhas'
    | '/_layoutmain/quiz'
    | '/_layoutmain/recolhas'
    | '/_layoutmain/reportes'
    | '/_layoutmain/rotas'
    | '/_layoutmain/utilizadores'
    | '/_layoutmain/zonas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutmainRoute: typeof LayoutmainRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layoutmain': {
      id: '/_layoutmain'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutmainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layoutmain/zonas': {
      id: '/_layoutmain/zonas'
      path: '/zonas'
      fullPath: '/zonas'
      preLoaderRoute: typeof LayoutmainZonasRouteImport
      parentRoute: typeof LayoutmainRoute
    }
    '/_layoutmain/utilizadores': {
      id: '/_layoutmain/utilizadores'
      path: '/utilizadores'
      fullPath: '/utilizadores'
      preLoaderRoute: typeof LayoutmainUtilizadoresRouteImport
      parentRoute: typeof LayoutmainRoute
    }
    '/_layoutmain/rotas': {
      id: '/_layoutmain/rotas'
      path: '/rotas'
      fullPath: '/rotas'
      preLoaderRoute: typeof LayoutmainRotasRouteImport
      parentRoute: typeof LayoutmainRoute
    }
    '/_layoutmain/reportes': {
      id: '/_layoutmain/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof LayoutmainReportesRouteImport
      parentRoute: typeof LayoutmainRoute
    }
    '/_layoutmain/recolhas': {
      id: '/_layoutmain/recolhas'
      path: '/recolhas'
      fullPath: '/recolhas'
      preLoaderRoute: typeof LayoutmainRecolhasRouteImport
      parentRoute: typeof LayoutmainRoute
    }
    '/_layoutmain/quiz': {
      id: '/_layoutmain/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof LayoutmainQuizRouteImport
      parentRoute: typeof LayoutmainRoute
    }
    '/_layoutmain/partilhas': {
      id: '/_layoutmain/partilhas'
      path: '/partilhas'
      fullPath: '/partilhas'
      preLoaderRoute: typeof LayoutmainPartilhasRouteImport
      parentRoute: typeof LayoutmainRoute
    }
    '/_layoutmain/noticias': {
      id: '/_layoutmain/noticias'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof LayoutmainNoticiasRouteImport
      parentRoute: typeof LayoutmainRoute
    }
    '/_layoutmain/mapa-sensores': {
      id: '/_layoutmain/mapa-sensores'
      path: '/mapa-sensores'
      fullPath: '/mapa-sensores'
      preLoaderRoute: typeof LayoutmainMapaSensoresRouteImport
      parentRoute: typeof LayoutmainRoute
    }
    '/_layoutmain/mapa': {
      id: '/_layoutmain/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof LayoutmainMapaRouteImport
      parentRoute: typeof LayoutmainRoute
    }
    '/_layoutmain/home': {
      id: '/_layoutmain/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof LayoutmainHomeRouteImport
      parentRoute: typeof LayoutmainRoute
    }
    '/_layoutmain/fila': {
      id: '/_layoutmain/fila'
      path: '/fila'
      fullPath: '/fila'
      preLoaderRoute: typeof LayoutmainFilaRouteImport
      parentRoute: typeof LayoutmainRoute
    }
    '/_layoutmain/ecopontos': {
      id: '/_layoutmain/ecopontos'
      path: '/ecopontos'
      fullPath: '/ecopontos'
      preLoaderRoute: typeof LayoutmainEcopontosRouteImport
      parentRoute: typeof LayoutmainRoute
    }
    '/_layoutmain/dashboard': {
      id: '/_layoutmain/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutmainDashboardRouteImport
      parentRoute: typeof LayoutmainRoute
    }
    '/_layoutmain/configuracoes': {
      id: '/_layoutmain/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof LayoutmainConfiguracoesRouteImport
      parentRoute: typeof LayoutmainRoute
    }
    '/_layoutmain/campanhas': {
      id: '/_layoutmain/campanhas'
      path: '/campanhas'
      fullPath: '/campanhas'
      preLoaderRoute: typeof LayoutmainCampanhasRouteImport
      parentRoute: typeof LayoutmainRoute
    }
    '/_layoutmain/audit': {
      id: '/_layoutmain/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof LayoutmainAuditRouteImport
      parentRoute: typeof LayoutmainRoute
    }
    '/_layoutmain/analytics': {
      id: '/_layoutmain/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof LayoutmainAnalyticsRouteImport
      parentRoute: typeof LayoutmainRoute
    }
  }
}

interface LayoutmainRouteChildren {
  LayoutmainAnalyticsRoute: typeof LayoutmainAnalyticsRoute
  LayoutmainAuditRoute: typeof LayoutmainAuditRoute
  LayoutmainCampanhasRoute: typeof LayoutmainCampanhasRoute
  LayoutmainConfiguracoesRoute: typeof LayoutmainConfiguracoesRoute
  LayoutmainDashboardRoute: typeof LayoutmainDashboardRoute
  LayoutmainEcopontosRoute: typeof LayoutmainEcopontosRoute
  LayoutmainFilaRoute: typeof LayoutmainFilaRoute
  LayoutmainHomeRoute: typeof LayoutmainHomeRoute
  LayoutmainMapaRoute: typeof LayoutmainMapaRoute
  LayoutmainMapaSensoresRoute: typeof LayoutmainMapaSensoresRoute
  LayoutmainNoticiasRoute: typeof LayoutmainNoticiasRoute
  LayoutmainPartilhasRoute: typeof LayoutmainPartilhasRoute
  LayoutmainQuizRoute: typeof LayoutmainQuizRoute
  LayoutmainRecolhasRoute: typeof LayoutmainRecolhasRoute
  LayoutmainReportesRoute: typeof LayoutmainReportesRoute
  LayoutmainRotasRoute: typeof LayoutmainRotasRoute
  LayoutmainUtilizadoresRoute: typeof LayoutmainUtilizadoresRoute
  LayoutmainZonasRoute: typeof LayoutmainZonasRoute
}

const LayoutmainRouteChildren: LayoutmainRouteChildren = {
  LayoutmainAnalyticsRoute: LayoutmainAnalyticsRoute,
  LayoutmainAuditRoute: LayoutmainAuditRoute,
  LayoutmainCampanhasRoute: LayoutmainCampanhasRoute,
  LayoutmainConfiguracoesRoute: LayoutmainConfiguracoesRoute,
  LayoutmainDashboardRoute: LayoutmainDashboardRoute,
  LayoutmainEcopontosRoute: LayoutmainEcopontosRoute,
  LayoutmainFilaRoute: LayoutmainFilaRoute,
  LayoutmainHomeRoute: LayoutmainHomeRoute,
  LayoutmainMapaRoute: LayoutmainMapaRoute,
  LayoutmainMapaSensoresRoute: LayoutmainMapaSensoresRoute,
  LayoutmainNoticiasRoute: LayoutmainNoticiasRoute,
  LayoutmainPartilhasRoute: LayoutmainPartilhasRoute,
  LayoutmainQuizRoute: LayoutmainQuizRoute,
  LayoutmainRecolhasRoute: LayoutmainRecolhasRoute,
  LayoutmainReportesRoute: LayoutmainReportesRoute,
  LayoutmainRotasRoute: LayoutmainRotasRoute,
  LayoutmainUtilizadoresRoute: LayoutmainUtilizadoresRoute,
  LayoutmainZonasRoute: LayoutmainZonasRoute,
}

const LayoutmainRouteWithChildren = LayoutmainRoute._addFileChildren(
  LayoutmainRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutmainRoute: LayoutmainRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
